"""T2.1: write a factual report about the dataset file. No modeling code.

Run from backend/:  python -m ml.inspect_data
"""

from pathlib import Path

import pandas as pd

from ml.config import (
    ARTIFACTS_DIR,
    BINARY_VALUES,
    DATA_PATH,
    DATA_SHEET,
    FEATURE_METADATA,
    FEATURES,
    TARGETS,
    VESSEL_IDS,
)
from ml.dataset import consistent_rows, encode_labels, file_sha256, read_sheet, stenotic_count

REPORT_NAME = "data_report.md"
MAX_LISTED_VALUES = 10


def _values(series: pd.Series) -> str:
    """Unique values if there are few, otherwise the range."""
    unique = series.unique()
    if len(unique) <= MAX_LISTED_VALUES:
        counts = series.value_counts()
        listed = sorted(unique, key=lambda value: (str(type(value)), value))
        return ", ".join(f"`{value}` ({counts[value]})" for value in listed)
    return f"{series.min():g} to {series.max():g}"


def _table(header: list[str], rows: list[list]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(str(cell) for cell in row) + " |" for row in rows]
    return lines


def _unmapped_values(raw: pd.DataFrame) -> dict[str, list]:
    problems = {}
    for feature in FEATURES:
        if feature.type == "numeric" or feature.source_column not in raw:
            continue
        mapping = BINARY_VALUES if feature.type == "binary" else feature.values
        unmapped = [value for value in raw[feature.source_column].unique() if value not in mapping]
        if unmapped:
            problems[feature.source_column] = unmapped
    return problems


def build_report(path: Path = DATA_PATH) -> str:
    raw = read_sheet(path)
    sheets = pd.ExcelFile(path).sheet_names
    input_columns = [column for column in raw.columns if column in FEATURE_METADATA]
    label_columns = [target.source_column for target in TARGETS]

    expected = set(FEATURE_METADATA) | set(label_columns)
    missing = sorted(expected - set(raw.columns))
    unexpected = sorted(set(raw.columns) - expected)
    unmapped = _unmapped_values(raw)
    bad_labels = {
        target.source_column: sorted(set(raw[target.source_column]) - {target.positive, target.negative})
        for target in TARGETS
        if target.source_column in raw
    }
    bad_labels = {column: values for column, values in bad_labels.items() if values}
    constant = [column for column in input_columns if raw[column].nunique() == 1]
    n_missing = int(raw.isna().sum().sum())
    n_duplicates = int(raw.duplicated().sum())

    lines = [
        "# Dataset inspection report",
        "",
        "Generated by `python -m ml.inspect_data` from the file below. Every number is computed "
        "from the file; nothing here involves a model.",
        "",
        "## 1. File",
        "",
        *_table(
            ["Property", "Value"],
            [
                ["File", f"`{path.name}`"],
                ["SHA-256", f"`{file_sha256(path)}`"],
                ["Sheets in workbook", ", ".join(f"`{sheet}`" for sheet in sheets)],
                ["Sheet read", f"`{DATA_SHEET}`"],
                ["Rows × columns", f"{raw.shape[0]} × {raw.shape[1]}"],
                ["Missing values", n_missing],
                ["Duplicate rows", n_duplicates],
            ],
        ),
        "",
        "## 2. Checks against DATA_MODEL (as encoded in `ml/config.py`)",
        "",
        *_table(
            ["Check", "Result"],
            [
                ["Columns missing from the file", ", ".join(missing) or "none"],
                ["Columns in the file without metadata", ", ".join(unexpected) or "none"],
                ["Input columns found", f"{len(input_columns)} of {len(FEATURE_METADATA)}"],
                ["Raw values without a canonical mapping", unmapped or "none"],
                ["Label values outside the expected set", bad_labels or "none"],
                ["Zero-variance input columns (dropped)", ", ".join(constant) or "none"],
            ],
        ),
        "",
    ]

    if not missing and not bad_labels:
        labels = encode_labels(raw)
        consistent = consistent_rows(labels)
        count = stenotic_count(labels)
        mismatched = labels.index[~consistent]
        lines += [
            "## 3. Labels",
            "",
            *_table(
                ["Target", "Column", "Positive value", "Positive", "Negative", "Prevalence"],
                [
                    [
                        target.id,
                        f"`{target.source_column}`",
                        f"`{target.positive}`",
                        int(labels[target.id].sum()),
                        int((labels[target.id] == 0).sum()),
                        f"{labels[target.id].mean():.3f}",
                    ]
                    for target in TARGETS
                ],
            ),
            "",
            "Number of stenotic vessels (LAD + LCX + RCA) per patient:",
            "",
            *_table(
                ["Stenotic vessels", "Patients"],
                [[k, int(n)] for k, n in count.value_counts().sort_index().items()],
            ),
            "",
            f"**Consistency.** Rows where `Cath` ≠ (LAD ∨ LCX ∨ RCA): **{len(mismatched)}**.",
        ]
        for row in mismatched:
            vessels = ", ".join(v.upper() for v in VESSEL_IDS if labels.at[row, v] == 1) or "none"
            lines.append(
                f"- Data row {row} (spreadsheet row {row + 2}): `Cath` = "
                f"`{raw.at[row, 'Cath']}`, stenotic vessels: {vessels}."
            )
        lines += [
            "",
            "Labels are never modified. Inconsistent rows stay in the training rows as recorded "
            "(D-040) and are not eligible as held-out sample patients (DATA_MODEL §5.3).",
            "",
        ]

    binary_01 = [f.source_column for f in FEATURES if f.type == "binary" and f.source_column in raw
                 and pd.api.types.is_numeric_dtype(raw[f.source_column])]
    binary_yn = [f.source_column for f in FEATURES if f.type == "binary" and f.source_column in raw
                 and f.source_column not in binary_01]
    lines += [
        "## 4. Derived-value checks",
        "",
        f"- Binary columns coded `0`/`1` ({len(binary_01)}): {', '.join(binary_01)}.",
        f"- Binary columns coded `N`/`Y` ({len(binary_yn)}): {', '.join(binary_yn)}.",
    ]
    if {"BMI", "Weight", "Length", "Obesity"} <= set(raw.columns):
        bmi = raw["Weight"] / (raw["Length"] / 100) ** 2
        agree = int(((raw["Obesity"] == "Y") == (raw["BMI"] > 25)).sum())
        lines += [
            "- `BMI` vs `Weight / (Length / 100)²`: largest absolute difference "
            f"{(raw['BMI'] - bmi).abs().max():.6f} (consistent with Weight in kg and Length in cm).",
            f"- `Obesity` = Y matches `BMI` > 25 in {agree} of {len(raw)} rows.",
        ]
    lines += [
        "",
        "## 5. Columns",
        "",
        *_table(
            ["#", "Column", "Feature id", "Type", "dtype", "Unique", "Values (count) or range"],
            [
                [
                    position,
                    f"`{column}`",
                    f"`{FEATURE_METADATA[column].id}`" if column in FEATURE_METADATA else "label",
                    FEATURE_METADATA[column].type if column in FEATURE_METADATA else "label",
                    raw[column].dtype,
                    raw[column].nunique(),
                    _values(raw[column]),
                ]
                for position, column in enumerate(raw.columns, start=1)
            ],
        ),
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    report = build_report()
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    target = ARTIFACTS_DIR / REPORT_NAME
    target.write_text(report, encoding="utf-8", newline="\n")
    print(f"Wrote {target}")


if __name__ == "__main__":
    main()
